apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense 
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
      project: expense
      tier: db
  serviceName: "mysql-headless" # name of the headless service
  replicas: {{ .Values.statefulset.replicas }} # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
        project: expense
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: peddireddylokesh/mysql:{{ .Values.statefulset.imageVersion }}
     
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
          #instead of creating  a pvc resource , we can directly provide in statefulset.
  volumeClaimTemplates:
  - metadata:
      name: mysql
      namespace: expense
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" # name of the storage class"
      resources:
        requests:
          storage: {{ .Values.statefulset.storage }}